### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by Mohit-robo** [yuntaeJ/SCIT-MCMT-Tracking#2]
Hey, I came across your work and found it great. Can you please provide the GT label files, just wanted to check the performance of the Multi cam tracker

**Comment by yuntaeJ** [comment]
Thanks, because of policy of the dataset I think I cannot provide it.
Maybe you can get the dataset from public site : https://www.aicitychallenge.org/2023-data-and-evaluation/

You can use there GT and evaluation metric for comparing with another teams also.
