### ISSUE TITLE
Training times

### ISSUE THREAD

**Issue by botasb** [yuntaeJ/SCIT-MCMT-Tracking#3]
Hi.
Very interesting paper and code. I am curious to know how long did it take you the trainings of the Yolox and Social-Implicit models.
Could you tell us?

Thanks a lot.

Kind regards,

**Comment by yuntaeJ** [comment]
Hello, I'm pleased that you're interested in it.

In case of Yolox, it took near 2~3 days based on the implementation detail in paper, and case of Social-Implicit it took near 0.5 day.

I hope this gives you a better understanding.
kind regards,
